[WIP] Use Difference operator for discrete system
SciML/ModelingToolkit.jl pull request #1119
Opened 2021-07-13 21:13 UTC by sharanry

https://github.com/SciML/ModelingToolkit.jl/issues/1088#issuecomment-876649631

TODO:

- [ ] Add utilities which enable handling Difference operators.
- [ ] Add difference function generators
- [ ] Add tests

2021-07-14 16:05 UTC, sharanry commented
@ChrisRackauckas @YingboMa The simple SIR test now works fine Difference operator. Is there any other more complex scenarios I can look at and support or is this sufficient for this initial PR?

2021-07-14 16:07 UTC, sharanry commented
Also, I think currently FunctionMap defaults `dt=1` [here](https://github.com/SciML/OrdinaryDiffEq.jl/blob/ba2a3a841614182a75c37e9e48b2c9ee82c60a0a/src/solve.jl#L26). I guess we will have to change that?

2021-07-14 16:10 UTC, sharanry commented
One other thing we are assuming right now is that we have a common difference operator on all states with equal timesteps. Do we intend to support multi-timestep processes?

2021-07-14 16:24 UTC, ChrisRackauckas commented
>Also, I think currently FunctionMap defaults to dt=1 here. I guess we will have to change that?

Yes.

2021-07-14 17:32 UTC, YingboMa commented on src/systems/discrete_system/discrete_system.jl
>      f(u,p,t) = f_oop(u,p,t)
Shouldn't there also be an in-place version as well?

2021-07-14 17:34 UTC, YingboMa commented on src/systems/discrete_system/discrete_system.jl
> +difference_vars(x::Sym) = Set([x])
Do you really need to copy-paste the `vars` code? What did you change?

2021-07-14 17:41 UTC, YingboMa commented on src/systems/discrete_system/discrete_system.jl
> +function collect_difference_variables(sys::DiscreteSystem)
Let's try not duplicate too much code. This code could be easily reused by making it a higher order function and pass in `isdifference`.

2021-07-14 17:42 UTC, YingboMa requested changes
The code copy-pasting seems easily avoidable.

2021-07-15 06:11 UTC, sharanry commented on src/systems/discrete_system/discrete_system.jl
>      f(u,p,t) = f_oop(u,p,t)
Yes. It does get generated. But not sure if we have any use for it in discrete systems as even solvers like `FunctionMap` uses the not-in-place function (not sure what it is called 😅 ).

2021-07-15 06:12 UTC, sharanry commented
Yup. I will try and refactor the code.

2021-07-15 11:49 UTC, sharanry commented
@YingboMa @ChrisRackauckas Does the ODESystem assume some kind of ordering of the equations in the differential system? It looks like the `generate_function` for ODESystem does not take into consideration what the LHS of each equation is. I also noticed [this TODO comment](https://github.com/SciML/ModelingToolkit.jl/blob/master/src/systems/diffeqs/abstractodesystem.jl#L112).

2021-07-15 15:27 UTC, YingboMa approved these changes
LGTM

2021-07-15 15:28 UTC, YingboMa commented
Oh, remember to also generalize the `vars!` function.

2021-07-15 15:32 UTC, sharanry commented
> Discrete system doesn't require it. Will add it in the difference operator in ODE system PR on which I have started a discussion [here](https://github.com/SciML/ModelingToolkit.jl/issues/1122)?

2021-07-15 15:34 UTC, YingboMa commented
Yes, handling `vars!` will be required for that issue, but let's do that in a future PR.

2021-07-15 15:34 UTC, merged