isisomorphic and convert_system fix
SciML/ModelingToolkit.jl pull request #1543
Opened 2022-04-29 23:50 UTC by anandijain

closes #1281

2022-04-30 17:16 UTC, YingboMa commented on Project.toml
> +Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
compat

2022-04-30 17:19 UTC, YingboMa commented on src/systems/diffeqs/abstractodesystem.jl
> +            elseif !isequal(eq, eq2) && j == length(eqs2)
Why checking this at all if you don't use it?

2022-04-30 17:20 UTC, YingboMa commented on src/systems/diffeqs/odesystem.jl
> +            ns = operation(s)(t; metadata=SymbolicUtils.metadata(s))
This should just be `similarterm`

2022-04-30 17:21 UTC, YingboMa requested changes
Checkout `similarterm`

2022-04-30 18:05 UTC, anandijain commented on src/systems/diffeqs/abstractodesystem.jl
> +            elseif !isequal(eq, eq2) && j == length(eqs2)
for fun

2022-05-01 17:26 UTC, YingboMa approved these changes
LGTM

2022-05-01 17:27 UTC, YingboMa commented
Test failure is unrelated.

2022-05-01 17:27 UTC, merged

2022-05-01 18:21 UTC, anandijain commented
Shouldn't I have removed the Symbolics.substitute dispatch first though?

2022-05-01 18:28 UTC, YingboMa commented
Ahhhh, yeah. Please do that.