Add `hessian_sparsity` method for `NonlinearSystem`
SciML/ModelingToolkit.jl pull request #1602
Opened 2022-05-25 13:09 UTC by Vaibhavdixit02

2022-05-25 13:17 UTC, ChrisRackauckas commented
Hess should probably get cached like the Jacobians?

2022-05-25 17:18 UTC, YingboMa commented
Run `format(".")` on the repo.

2022-05-25 17:19 UTC, YingboMa requested changes
Tests?

2022-05-26 05:30 UTC, Vaibhavdixit02 commented on Project.toml
> +JuliaFormatter = "1"
Since `"scimlstyle"` only works for v1 I think we should drop the older compat?

2022-05-26 11:24 UTC, ChrisRackauckas commented on src/systems/optimization/optimizationsystem.jl
> +                                              nothing,
If sparse is true, then this needs to give the prototype matrices.

2022-05-27 01:10 UTC, ChrisRackauckas commented
It's a little janky to just have a Hessian function without it being in the NonlinearProblem and NonlinearFunction constructors, but since there isn't a single nonlinear solver method right now that wants said Hessian I guess it's fine and can always be added later.

2022-05-27 01:11 UTC, ChrisRackauckas commented
Plus it fixes master.

2022-05-27 01:11 UTC, ChrisRackauckas commented
Formatter failed.

2022-05-27 03:59 UTC, merged