Improves OptimizationSystem
SciML/ModelingToolkit.jl pull request #1787
Opened 2022-08-28 14:17 UTC by ValentinKaisermayer

2022-08-28 14:18 UTC, ValentinKaisermayer commented
closes #1785

2022-08-28 14:40 UTC, ValentinKaisermayer commented on src/systems/optimization/optimizationsystem.jl
> +            op isa Num && check_units(op)
I'm not sure about this. The intended use-case is when one system has no objective function i.e. just `0` but sub-systems do have one.

2022-08-29 16:21 UTC, YingboMa commented on src/systems/optimization/optimizationsystem.jl
> +            op isa Num && check_units(op)
MTK should never work with Num. You should always unwrap it and then check if it's Symbolic.

2022-08-29 21:16 UTC, YingboMa approved these changes

2022-08-29 21:17 UTC, YingboMa commented on src/systems/abstractsystem.jl
> -             :inequality_constraints
`:constraints` should be here.

2022-08-29 21:17 UTC, YingboMa commented on src/systems/optimization/optimizationsystem.jl
> +get_constraints(sys::OptimizationSystem) = value(sys.constraints)
`sys.x` means getting the variable named `x` from `sys`.

2022-08-29 21:18 UTC, YingboMa requested changes
`sys.constraints` is deprecated.

2022-08-31 13:36 UTC, YingboMa commented on src/systems/optimization/optimizationsystem.jl
> +# namespace_constraint(ineq::Inequality, sys) = namespace_inequality(ineq, sys)
Why are they removed?

2022-08-31 17:28 UTC, ValentinKaisermayer commented on src/systems/optimization/optimizationsystem.jl
> +# namespace_constraint(ineq::Inequality, sys) = namespace_inequality(ineq, sys)
They are not removed but rather I put them in and commented them out. Needs https://github.com/JuliaSymbolics/Symbolics.jl/pull/717 first

2022-08-31 18:19 UTC, YingboMa commented
The CI failure looks real.

2022-08-31 18:36 UTC, YingboMa commented
Format

2022-08-31 18:38 UTC, ValentinKaisermayer commented
I swear I did that:
```julia
(@v1.8) pkg> st
Status .julia\environments\v1.8\Project.toml`
  [70b36510] AutomaticDocstrings v1.0.5
  [98e50ef6] JuliaFormatter v1.0.9
  [295af30f] Revise v3.4.0

julia> format(".")
true
```

2022-08-31 18:42 UTC, ChrisRackauckas commented
using the SciML format?

2022-08-31 18:45 UTC, ValentinKaisermayer commented
Isn't that picked up automatically from the `.JuliaFormatter.toml`?

2022-08-31 18:52 UTC, ValentinKaisermayer commented
Just to make sure
```
julia> JuliaFormatter.format("."; style=JuliaFormatter.SciMLStyle)
true
```

2022-08-31 21:20 UTC, YingboMa commented
The format failure is due to https://github.com/SciML/ModelingToolkit.jl/commit/56ce7e5aae0e72786cf6666532173d5f455f8d3f . @baggepinnen please don't commit on master directly, and if you did it by mistake, please revert it if the CI fails.

2022-08-31 22:48 UTC, merged

2022-09-01 05:11 UTC, baggepinnen commented
Sorry about that :( I was trying to figure out how I managed to commit straight to master, and I think it's because edits in the web interface defaults to committing instead of opening a PR
![image](https://user-images.githubusercontent.com/3797491/187835851-077d792c-63c2-48ad-b685-49f1d6b953be.png)
is there some way to make opening the PR the default option, like a branch-protection rule? I hadn't even noticed that I already committed :/