fixes input output handling for array variables
SciML/ModelingToolkit.jl pull request #1808
Opened 2022-09-03 19:38 UTC by ValentinKaisermayer

2022-09-03 19:45 UTC, ValentinKaisermayer commented
closes #1808

2022-09-03 23:55 UTC, YingboMa requested changes
The CI failure is real.

2022-09-04 05:54 UTC, ValentinKaisermayer commented
Looks real but at first glance unrelated, #1806 has the same problem.

2022-09-09 17:59 UTC, YingboMa approved these changes

2022-09-09 17:59 UTC, merged