Fix Metadata - Integration tests passing on MOL
SciML/ModelingToolkit.jl pull request #1814
Opened 2022-09-08 17:49 UTC by xtalax

I had made a mistake on https://github.com/SciML/ModelingToolkit.jl/pull/1768, neglecting to add `nothing` to pad the arguments of the constructor so that metadata was in the right place. 
This fixes that issue.
This has been tested locally in MOL, and works there.

2022-09-08 20:30 UTC, ChrisRackauckas commented
Can you add tests?

2022-09-09 13:47 UTC, xtalax commented
Tested

2022-09-09 13:50 UTC, ChrisRackauckas approved these changes

2022-09-09 14:54 UTC, YingboMa commented
CI and format checker fails.

2022-09-09 14:55 UTC, YingboMa commented on src/ModelingToolkit.jl
> +import SciMLBase: StandardODEProblem
Where is this used?

2022-09-09 14:57 UTC, YingboMa requested changes
Won't it be easier if you just reorder the metadata field?

2022-09-09 15:51 UTC, xtalax commented
> Won't it be easier if you just reorder the metadata field?

Leads to this error when reordered
```
  type TearingState has no field deps
  Stacktrace:
    [1] getproperty(x::TearingState{NonlinearSystem}, f::Symbol)
      @ Base ./Base.jl:33
    [2] empty_substitutions(sys::NonlinearSystem)
      @ ModelingToolkit ~/.julia/dev/ModelingToolkit.jl/src/utils.jl:541
    [3] get_substitutions_and_solved_states(sys::NonlinearSystem; no_postprocess::Bool)
      @ ModelingToolkit ~/.julia/dev/ModelingToolkit.jl/src/utils.jl:545
    [4] get_substitutions_and_solved_states
      @ ~/.julia/dev/ModelingToolkit.jl/src/utils.jl:545 [inlined]
    [5] generate_function(sys::NonlinearSystem, dvs::Vector{Term{Real, Nothing}}, ps::Vector{Any}; kwargs::Base.Iterators.Pairs{Symbol, Any, NTuple{5, Symbol}, NamedTuple{(:expression, :checkbounds, :linenumbers, :parallel, :check_length), Tuple{DataType, Bool, Bool, Nothing, Bool}}})
      @ ModelingToolkit ~/.julia/dev/ModelingToolkit.jl/src/systems/nonlinear/nonlinearsystem.jl:174
    [6] (NonlinearFunction{true, recompile, F, TMM, Ta, Tt, TJ, JVP, VJP, JP, SP, TW, TWt, TPJ, S, O, TCV, SYS} where {recompile, F, TMM, Ta, Tt, TJ, JVP, VJP, JP, SP, TW, TWt, TPJ, S, O, TCV, SYS})(sys::NonlinearSystem, dvs::Vector{Term{Real, Nothing}}, ps::Vector{Any}, u0::Vector{Float64}; version::Nothing, jac::Bool, eval_expression::Bool, sparse::Bool, simplify::Bool, kwargs::Base.Iterators.Pairs{Symbol, Union{Nothing, Bool}, NTuple{4, Symbol}, NamedTuple{(:checkbounds, :linenumbers, :parallel, :check_length), Tuple{Bool, Bool, Nothing, Bool}}})
      @ ModelingToolkit ~/.julia/dev/ModelingToolkit.jl/src/systems/nonlinear/nonlinearsystem.jl:215
    [7] process_NonlinearProblem(constructor::Type, sys::NonlinearSystem, u0map::Vector{Float64}, parammap::SciMLBase.NullParameters; version::Nothing, jac::Bool, checkbounds::Bool, sparse::Bool, simplify::Bool, linenumbers::Bool, parallel::Nothing, eval_expression::Bool, use_union::Bool, kwargs::Base.Iterators.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:check_length,), Tuple{Bool}}})
      @ ModelingToolkit ~/.julia/dev/ModelingToolkit.jl/src/systems/nonlinear/nonlinearsystem.jl:319
    [8] (NonlinearProblem{true, isinplace, P, F, K} where {isinplace, P, F, K})(sys::NonlinearSystem, u0map::Vector{Float64}, parammap::SciMLBase.NullParameters; check_length::Bool, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
      @ ModelingToolkit ~/.julia/dev/ModelingToolkit.jl/src/systems/nonlinear/nonlinearsystem.jl:345
    [9] NonlinearProblem (repeats 2 times)
      @ ~/.julia/dev/ModelingToolkit.jl/src/systems/nonlinear/nonlinearsystem.jl:345 [inlined]
   [10] #NonlinearProblem#607
      @ ~/.julia/dev/ModelingToolkit.jl/src/systems/nonlinear/nonlinearsystem.jl:339 [inlined]
   [11] NonlinearProblem(sys::NonlinearSystem, args::Vector{Float64})
      @ ModelingToolkit ~/.julia/dev/ModelingToolkit.jl/src/systems/nonlinear/nonlinearsystem.jl:339
...
```

2022-09-09 15:51 UTC, YingboMa commented
You need to reorder the constructor arguments as well.

2022-09-09 15:55 UTC, xtalax commented
I did, of course. Changing the internal constructor arguments and the call to it in the external constructor, leads to this error. I think this shows that it will not be easier to just reorder the constructor.

2022-09-09 17:38 UTC, xtalax commented
IMPORTANT: this depends on https://github.com/SciML/SciMLBase.jl/pull/246

2022-09-09 17:52 UTC, xtalax commented on src/ModelingToolkit.jl
> +import SciMLBase: StandardODEProblem
as the default for problem_type when metadata is `nothing`

2022-09-09 17:58 UTC, xtalax commented
@YingboMa I think it's definitely easier to leave the constructor as is, it seems that the inner constructor is called in multiple places and your requested change would require tracking down each of those calls - I don't know where these are, errors occur later than this/these call/calls so this is hard for me to do without complete knowledge of the package.

2022-09-09 18:01 UTC, YingboMa commented on src/systems/nonlinear/nonlinearsystem.jl
> +    pt = if get_metadata(sys) === nothing
`something(get_metadata(sys), StandardNonlinearProblem())`?

2022-09-09 18:16 UTC, xtalax commented on src/systems/nonlinear/nonlinearsystem.jl
> +    pt = if get_metadata(sys) === nothing
I didn't know about something, thanks.

2022-09-14 13:04 UTC, ChrisRackauckas commented
Tests fail?

2022-09-14 17:50 UTC, YingboMa commented on src/ModelingToolkit.jl
> +       observed, structure, full_equations, get_metadata
No other `get_` functions are exported.

2022-09-14 17:54 UTC, YingboMa commented on test/optimizationsystem.jl
> +    @test sys1.metadata == testdict
Don't use `metadata`.

2022-09-14 17:54 UTC, YingboMa commented on test/nonlinearsystem.jl
> +    @test sys.metadata == testdict
same here.

2022-09-14 17:55 UTC, YingboMa requested changes
What about `metadata` for other systems? Also, you should move the metadata field before the internal fields, so you won't need `nothing, nothing`.

2022-09-14 18:20 UTC, closed without merging