Add DiscreteFunction
SciML/ModelingToolkit.jl pull request #2058
Opened 2023-02-01 10:26 UTC by ErikQQY

Part of #993

2023-02-03 12:15 UTC, ChrisRackauckas commented on test/discretesystem.jl
> +df = NonlinearFunction(sys)
```suggestion
df = DiscreteFunction(sys)
```

2023-02-03 12:15 UTC, ChrisRackauckas approved these changes

2023-02-03 19:18 UTC, YingboMa requested changes
Needs formatting and tests. See https://github.com/SciML/ModelingToolkit.jl/blob/master/CONTRIBUTING.md

2023-02-04 08:05 UTC, ErikQQY commented
The out-of-place tests are fine, but I still can't figure out what is wrong with the inplace discrete functions.

![image](https://user-images.githubusercontent.com/52615090/216756360-9895a7c2-1425-4921-b6dc-238b30f0048a.png)

2023-02-04 12:59 UTC, YingboMa commented
Isn't `f(u, p, t)` out-of-place? You can inspect the function body by printing `f.body` if `f` is a RuntimeGeneratedFunction.

2023-02-04 17:18 UTC, ErikQQY commented
Yeah, made a mistake, ```f(u, p, t)``` is out-of-place🥲.

Just fixed all of the tests!

2023-02-05 00:46 UTC, ChrisRackauckas approved these changes

2023-02-05 01:36 UTC, ChrisRackauckas commented
@YingboMa what's going on with the docs failure?

2023-02-05 03:10 UTC, merged

2023-02-05 03:10 UTC, YingboMa commented
I will take a look on Monday.