fix: change `f` to a random symbol in `component_post_processing`
SciML/ModelingToolkit.jl pull request #2105
Opened 2023-03-01 14:34 UTC by ven-k

- This allows to define components with `f` as arg

Fixes this error:
```julia
julia> @component function A(; name, f)
           ODESystem(Equations[], t, [], []; name=name)
       end
ERROR: syntax: cannot add method to function argument f
Stacktrace:
 [1] top-level scope
   @ REPL[3]:1
```

2023-03-01 16:12 UTC, baggepinnen commented
You could probably use `gensym` which is intended for exactly this?

2023-03-01 16:20 UTC, ChrisRackauckas commented on src/systems/abstractsystem.jl
> +            res = $rand_f()
why is this good? Won't this cause recompilation when applied to the same model?

2023-03-01 16:31 UTC, ven-k commented on src/systems/abstractsystem.jl
> +            res = $rand_f()
Didn't consider that. I wanted it to pick a name that is unlikely to be passed as an argument.
gensym would be a better bet for that. But I'm wondering - that would run into same recompilation issue.

Perhaps `modelingtoolkit_f` is unlikely enough?

2023-03-01 19:26 UTC, ven-k commented on src/systems/abstractsystem.jl
> +            res = $rand_f()
Switched to using `gensym` to avoid any name clash.

2023-03-03 09:25 UTC, ChrisRackauckas commented on src/systems/abstractsystem.jl
>                  $body
wait, why is a closure needed at all?

2023-03-03 10:25 UTC, ven-k commented on src/systems/abstractsystem.jl
>                  $body
Actually yeah 😅

2023-03-04 05:08 UTC, YingboMa commented
> wait, why is a closure needed at all?

Because the body could contain explicit `return`

2023-03-04 05:09 UTC, YingboMa requested changes
A closure is necessary for correctness

2023-03-04 05:17 UTC, YingboMa commented
superseded by #2107

2023-03-04 05:17 UTC, closed without merging