Parse the args in extended components
SciML/ModelingToolkit.jl pull request #2202
Opened 2023-06-29 12:07 UTC by ven-k

- Additionally, assign the default values of vars/pars to the kwargs of components 
- And when no defaults are specified (in @ components), set `nothing` as the default

2023-06-29 18:13 UTC, ven-k commented
Can this test: https://github.com/SciML/ModelingToolkit.jl/actions/runs/5411992983/jobs/9835489223?pr=2202 be retriggered?

The failing test[^1] is unrelated to this PR.
And the tol looks very close:
```
JumpSystem Test: Test Failed at /home/runner/work/ModelingToolkit.jl/ModelingToolkit.jl/test/jumpsystem.jl:127
  Expression: abs(m - m2) / m < 0.01
   Evaluated: 0.010271246180714049 < 0.01
```

[^1]:https://github.com/SciML/ModelingToolkit.jl/actions/runs/5411992983/jobs/9835489223?pr=2202#step:6:986

2023-06-30 03:52 UTC, baggepinnen commented
> Can this test: https://github.com/SciML/ModelingToolkit.jl/actions/runs/5411992983/jobs/9835489223?pr=2202 be retriggered?

I retriggered it, but the test framework internally sets the random seed in the beginning of each testset in order to make failures reproducible, so retriggering might not work. Maybe the test tolerance should be increased?

2023-06-30 10:29 UTC, isaacsas requested changes

2023-06-30 10:29 UTC, isaacsas commented on test/jumpsystem.jl
> +@test round(abs(m - m2) / m, digits = 3) < 0.01
Please don’t modify this check like this or change the tolerance of the check. 

Instead, add and use StableRNGs with a fixed seed as the rng, see this file for usage: 

https://github.com/SciML/JumpProcesses.jl/blob/master/test/bimolerx_test.jl

2023-06-30 14:47 UTC, ven-k commented on test/jumpsystem.jl
> +@test round(abs(m - m2) / m, digits = 3) < 0.01
Addressed with: https://github.com/SciML/ModelingToolkit.jl/pull/2202/commits/fa0a4bbe1a737f1e025cd2c830e442f11446001e

2023-06-30 18:54 UTC, isaacsas commented on test/jumpsystem.jl
> +@test round(abs(m - m2) / m, digits = 3) < 0.01
Thanks!

2023-07-03 19:11 UTC, YingboMa commented on test/model_parsing.jl
> +        v = 0.0
Can we have a test for this?

2023-07-03 19:13 UTC, merged

2023-07-04 06:59 UTC, ven-k commented on test/model_parsing.jl
> +        v = 0.0
Ok. Will add along the Model.structure[:connectors] PR.