Refactor tutorials with `@mtkmodel`
SciML/ModelingToolkit.jl pull request #2286
Opened 2023-09-27 09:23 UTC by ven-k

- Refactors following tutorials with `@mtkmodel`
    - Acausal components 
    - Structural identifiability
- Enlists `@mtkmodel` docpage in under "Basics" section

2023-09-30 13:11 UTC, ChrisRackauckas commented
What's left to merge?

2023-10-02 01:16 UTC, ArnoStrouwen commented
Could you retrigger CI @ChrisRackauckas?
I can at least resolve locally now.

2023-10-02 01:18 UTC, ChrisRackauckas commented
Needs to be resolved to trigger.

2023-10-02 02:15 UTC, ArnoStrouwen requested changes
Fix for the SI tutorial.

2023-10-02 02:15 UTC, ArnoStrouwen commented on docs/src/tutorials/parameter_identifiability.md
> +        D = Differential(t)
```suggestion
        @variables t
        D = Differential(t)
```

2023-10-02 02:15 UTC, ArnoStrouwen commented on docs/src/tutorials/parameter_identifiability.md
>  to_check = [k5, k7, k10 / k9, k5 + k6]
```suggestion
@unpack k5, k6, k7, k9, k10 = de
to_check = [k5, k7, k10 / k9, k5 + k6]
```

2023-10-02 10:50 UTC, ven-k commented
> What's left to merge?

I'm refactoring the "Getting started" based on Friday's discussion. I'm planning to make a copy of it with `@mtkmodel` and rename the current "Getting started" as "Introduction to non-DSL based ModelingToolkit" (with maybe a little bit of minor cuts).

2023-10-02 10:50 UTC, ven-k commented on docs/src/tutorials/parameter_identifiability.md
> +        D = Differential(t)
Will resolve the conflicts and commit this in.

2023-10-02 18:09 UTC, ArnoStrouwen commented
I think the `@connector` macro needs a similar thorough explanation as the `@mtkmodel` macro is getting
Specifically, where Flow comes from.

Having docstrigns for both would also be a plus.

2023-10-04 13:29 UTC, ven-k commented
Note that these have changed since the previous push:

- Refactors "Getting Started" page to use `@mtkmodel` and adds a note on using `complete`
- Adds "Components" and "Connectors" section to MTKModel-Connector docs-page.
- And elaborates what `Model.structure` is.
- Adds `connect` section in Variable metadata
- Updates ContextualVariables.md with `get_unit` and `VariableUnit`

2023-10-04 19:36 UTC, YingboMa commented
What does it take to fix the Documentation CI?

2023-10-05 06:46 UTC, ven-k commented
- https://github.com/SciML/StructuralIdentifiability.jl/issues/216

2023-10-07 18:38 UTC, ChrisRackauckas commented
what's left to merge?

2023-10-08 04:29 UTC, ven-k commented
I'll retrigger docs build.

2023-10-08 08:06 UTC, ChrisRackauckas commented
Let's merge and follow up with more changes.

2023-10-08 08:06 UTC, merged