feat: initial implementation of new `DiscreteSystem`
SciML/ModelingToolkit.jl pull request #2507
Opened 2024-02-28 20:12 UTC by AayushSabharwal

## Checklist

- [ ] Appropriate tests were added
- [ ] Any code changes were done in a way that does not break public API
- [ ] All documentation related to code changes were updated
- [ ] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [ ] Any new documentation only uses public API
  
## Additional context

Add any other context about the problem here.

2024-02-29 03:38 UTC, baggepinnen commented on src/systems/discrete_system/discrete_system.jl
> +D = Difference(t; dt=δt)
Needs update?

2024-02-29 03:38 UTC, baggepinnen commented on src/systems/discrete_system/discrete_system.jl
> +    ctrls::Vector
should go away?

2024-02-29 03:38 UTC, baggepinnen commented on src/systems/discrete_system/discrete_system.jl
> +    function DiscreteSystem(tag, discreteEqs, iv, dvs, ps, tspan, var_to_name, ctrls,
ctrls

2024-02-29 03:38 UTC, baggepinnen commented on src/systems/discrete_system/discrete_system.jl
> +        controls = Num[],
```suggestion
```

2024-02-29 03:53 UTC, baggepinnen commented
The old discrete systems had a lot of correctness issues. Some of the issues reporting those have been closed since the old stuff was removed, but it would probably still be good to add the reported MWEs to the tests. Looking through the old issues, many were related to algebraic variables, such as
- https://github.com/SciML/ModelingToolkit.jl/issues/1330

Perhaps adding an error if not all equations are difference equations would be sufficient for now?

2024-03-04 12:30 UTC, ChrisRackauckas commented on src/systems/systems.jl
> +    # end
what's this commented for?

2024-03-04 13:07 UTC, AayushSabharwal commented on src/systems/systems.jl
> +    # end
That should have been deleted

2024-03-04 13:23 UTC, AayushSabharwal commented on src/systems/systems.jl
> +    # end
Fixed in https://github.com/SciML/ModelingToolkit.jl/pull/2507/commits/e59639325e9db3bd5105b33851812a737c3629a3

2024-03-04 13:43 UTC, ChrisRackauckas commented on docs/src/tutorials/discrete_system.md
> +for the Fibonacci series as `x ~ x(k-1) + x(k-2)` use `x(k+2) ~ x(k+1) + x`.
Let's not touch that right now 😅 . Just remove that from the docs

2024-03-04 13:43 UTC, ChrisRackauckas commented on docs/src/tutorials/discrete_system.md
> +# Modeling Discrete Systems
Mark as experimental until the indexing thing is solidified.

2024-03-04 14:52 UTC, YingboMa commented on src/discretedomain.jl
> +normalize_to_differential(s::Shift) = Differential(s.t)^abs(s.steps)
This is not correct. It changes `u(k)~u(k-2)-u(k-1)` to `u(k)~u(k+2)-u(k+1)` which obviously isn't the same.

2024-03-04 14:54 UTC, YingboMa reviewed
Let's support non-positive shift properly before merging.

2024-03-13 09:37 UTC, AayushSabharwal commented
https://github.com/SciML/ModelingToolkit.jl/pull/2507/commits/d9891cbbaad21e89766a3843c98c916e7f4b987f fixes a bug introduced by #2537

2024-03-13 10:58 UTC, ChrisRackauckas commented on docs/src/tutorials/discrete_system.md
> +tspan = (0.0, 100.0) # value function (from Symbolics) is used to convert a Num to Float64
what does this comment mean?

2024-03-13 10:58 UTC, ChrisRackauckas commented on docs/src/tutorials/discrete_system.md
> +for the Fibonacci series as `x ~ x(k-1) + x(k-2)` use `x(k+2) ~ x(k+1) + x`.
Is this still correct?

2024-03-13 10:58 UTC, ChrisRackauckas commented on src/discretedomain.jl
> +normalize_to_differential(s::Shift) = Differential(s.t)^abs(s.steps)
bump

2024-03-13 11:20 UTC, AayushSabharwal commented on docs/src/tutorials/discrete_system.md
> +tspan = (0.0, 100.0) # value function (from Symbolics) is used to convert a Num to Float64
It means I copied the example from tests and didn't notice the comment 😅

2024-03-13 11:44 UTC, AayushSabharwal commented on docs/src/tutorials/discrete_system.md
> +for the Fibonacci series as `x ~ x(k-1) + x(k-2)` use `x(k+2) ~ x(k+1) + x`.
Fixed

2024-03-13 11:44 UTC, AayushSabharwal commented on docs/src/tutorials/discrete_system.md
> +# Modeling Discrete Systems
Fixed

2024-03-13 11:44 UTC, AayushSabharwal commented on src/discretedomain.jl
> +normalize_to_differential(s::Shift) = Differential(s.t)^abs(s.steps)
Fixed

2024-03-13 11:44 UTC, AayushSabharwal commented on docs/src/tutorials/discrete_system.md
> +tspan = (0.0, 100.0) # value function (from Symbolics) is used to convert a Num to Float64
Fixed

2024-03-13 12:07 UTC, AayushSabharwal commented
Codecov is _very_ unhappy for some reason?

2024-03-13 21:40 UTC, ChrisRackauckas commented
Something happened with the docs example? https://github.com/SciML/ModelingToolkit.jl/actions/runs/8264109678/job/22607005589?pr=2507#step:6:1747

2024-03-14 07:08 UTC, AayushSabharwal commented
Docs don't want to build for some reason.

I also found a minor bug, but it is caused by the changes in this PR so merging this will have to wait a little bit

2024-03-14 10:35 UTC, AayushSabharwal commented
Technically this requires https://github.com/JuliaSymbolics/Symbolics.jl/pull/1090

2024-03-14 15:46 UTC, ChrisRackauckas approved these changes

2024-03-14 16:34 UTC, YingboMa requested changes
We cannot merge this before it's uses ONLY non-positive shifts.

2024-03-18 08:12 UTC, AayushSabharwal commented
Non-positive shifts are enforced. Only thing that's left is to make `observed` work with discrete-time variables

2024-03-18 13:23 UTC, YingboMa commented on src/structural_transformation/utils.jl
> +    r = @rule ~x::isdoubleshift => begin
I think the rule system drops metadata. Are you sure that this doesn't cause problems later on?

2024-03-18 13:25 UTC, AayushSabharwal commented on src/structural_transformation/utils.jl
> +    r = @rule ~x::isdoubleshift => begin
I'll check if it drops metadata. In case it does, I'll rewrite this as a recursive function

2024-03-18 13:27 UTC, YingboMa commented on src/structural_transformation/symbolics_tearing.jl
> +                dx = D(simplify_shifts(lower_varname_withshift(
Why is the `lower_varname_withshift` inside a `isdervar` branch?

2024-03-18 13:27 UTC, YingboMa commented on src/structural_transformation/symbolics_tearing.jl
> +                dx = D(simplify_shifts(lower_varname_withshift(
Ah, that's the structural info.

2024-03-18 13:30 UTC, YingboMa commented on src/systems/diffeqs/odesystem.jl
> +        op = Union{Differential, Shift},
Why not just `Operator`?

2024-03-18 13:45 UTC, AayushSabharwal commented on src/structural_transformation/utils.jl
> +    r = @rule ~x::isdoubleshift => begin
Fixed in https://github.com/SciML/ModelingToolkit.jl/pull/2507/commits/33da074d039e47ed7d46e0854dabf42f8a2c2673

2024-03-18 14:04 UTC, YingboMa commented
@baggepinnen could you review the updated tests?

2024-03-18 14:07 UTC, YingboMa commented on src/structural_transformation/utils.jl
> +    if isdoubleshift(var)
What about triple shifts? Should we recurse on that, too?

2024-03-18 14:19 UTC, baggepinnen commented on docs/src/tutorials/discrete_system.md
> +All shifts must be negative. If default values are provided, they are treated as the value
```suggestion
All shifts must be non-positive, i.e., discrete-time variables may only be indexed at index `k, k-1, k-2, ...`. If default values are provided, they are treated as the value
```

2024-03-18 14:19 UTC, baggepinnen commented on test/clock.jl
> -       z(k + 2) ~ z(k) + yd
the purpose of this contrived example was to test multi-step shifts, I don't see any multi-step tests anymore?

2024-03-18 14:51 UTC, AayushSabharwal commented
I can't replicate the Optimization bugs, even with the same environment checked out

2024-03-18 15:18 UTC, AayushSabharwal commented on test/clock.jl
> -       z(k + 2) ~ z(k) + yd
Fixed

2024-03-18 15:18 UTC, AayushSabharwal commented on docs/src/tutorials/discrete_system.md
> +All shifts must be negative. If default values are provided, they are treated as the value
Fixed

2024-03-18 15:18 UTC, AayushSabharwal commented on src/structural_transformation/utils.jl
> +    if isdoubleshift(var)
Fixed

2024-03-18 16:44 UTC, baggepinnen commented on test/clock.jl
>  sol = solve(prob, Tsit5(), kwargshandle = KeywordArgSilent)
I added this test here
```julia
#      kp  yd(0)  ud(k-1)
ud_0 = 1 * 0.1    + 2; # This computes what ud should be at time t = 0
@test sol(0+eps(), Val{1})[] ≈ -sol(0+eps(), idxs=x) + ud_0
```
it fails. I check that 
`D(x)(t=0)` is correctly calculated (I got errors trying to access `sol(0, idxs=D(x))` by adding `-x(0)` and `ud(0)`

2024-03-19 06:12 UTC, AayushSabharwal commented on test/clock.jl
>  sol = solve(prob, Tsit5(), kwargshandle = KeywordArgSilent)
So this discrepancy is because the init function returned by clock inference codegen needs to also perform a discrete update, since the unknowns are now `ud(k-1)` and `ud(k-2)` (past values). Currently, it interprets `ud(k-1)` as the value of `ud` at `t=0`. This sort of discrepancy comes about because the unknowns are named `ud(k-1)` and `ud(k-2)` which implies that they are past values. However, after the `affect!` function is run, the value of `ud(k-1)` is the value of `ud` _at the current time_. Problem initialization assumes that the initial values are the ones after `affect!` has been run, so to speak

2024-03-19 06:16 UTC, AayushSabharwal commented on test/clock.jl
>  sol = solve(prob, Tsit5(), kwargshandle = KeywordArgSilent)
With this interpretation, the value of `1.9` returned by `sol(0+eps(), Val{1})` in this example is correct, since `ud` at the current time is considered to be `2.0` and `x` is `0.1`

2024-03-19 06:48 UTC, baggepinnen commented on test/clock.jl
>  sol = solve(prob, Tsit5(), kwargshandle = KeywordArgSilent)
> Currently, it interprets ud(k-1) as the value of ud at t=0

Then we should change this. At each tick of the clock, `x(k)` refers to the new value at the tick time, so `ud(k)` refers to the value of `ud` _after_ the clock has ticked at t = 0, while `ud(k-1)` refers to the first past value (before t=0). 

The shift-index notation $x(k)$ is standard in the literature of discrete-time systems and is short for $x(t_0 + k \Delta T)$ where $\Delta T$ is the tick interval of the clock. A discrete-time difference equation describes something that holds true for all $k$, if we insert the start time $t_0 = 0$ and $k=0$ in the equation for `ud`, we get the value of `ud` at the initial time `ud(0) = kp*yd(0) + ud(-1)`

The reason I took the time to clone this PR and add this test is that these details are extremely important. The old discrete-time functionality that we threw away had a lot of small nuances like this left undocumented and untested, and as a result it was completely impossible to rely on it for any serious real-world use case. I want to avoid going back to the same situation again, it's worth spending the time to get this right :)

2024-03-19 07:12 UTC, baggepinnen commented on test/clock.jl
>  sol = solve(prob, Tsit5(), kwargshandle = KeywordArgSilent)
> This sort of discrepancy comes about because the unknowns are named ud(k-1) and ud(k-2) 

This is an implementation detail and should not influence how the system behaves from the perspective of the user. We can call the unknowns `Aayush` and `Fredrik` if it makes it less confusing :) 

The choice of state `ud(k-1), ud(k-2) ` is a slightly strange, we are solving for `ud(k)`, so I would probably have chosen this variable to be part of the state rather than the two past values, c.f.
https://juliahub.slack.com/archives/C03UEC0P6G0/p1710482554351029?thread_ts=1710481464.183949&cid=C03UEC0P6G0

2024-03-19 07:29 UTC, AayushSabharwal commented on test/clock.jl
>  sol = solve(prob, Tsit5(), kwargshandle = KeywordArgSilent)
> Then we should change this

yeah that's what I'm working on right now

> The choice of state ud(k-1), ud(k-2) is a slightly strange, we are solving for ud(k), so I would probably have chosen this variable to be part of the state rather than the two past values

It's somewhat of an artifact of using nonpositive shifts. Consider the continuous-time case, where `D(D(x)) ~ f(D(x), x)`. We take `x` and `D(x)` (the lowest order terms) as the unknowns, and compute `D(D(x))`. `D(D(x))` isn't actually a symbolic variable in this case. Similarly, for `x(k) ~ f(x(k-1), x(k-2))` we take `x(k-1) and `x(k-2)` as the unknowns, and compute `x(k)` which is now reinterpreted as "the next value of `x(k-1)`".

2024-03-19 08:02 UTC, AayushSabharwal commented
The optimization errors seem to be due to bugs upstream in the Optimization stack. The generated functions look good to me, it's probably an error with how they're called

2024-03-19 08:16 UTC, AayushSabharwal commented on test/clock.jl
>  sol = solve(prob, Tsit5(), kwargshandle = KeywordArgSilent)
Fixed now

2024-03-19 09:19 UTC, baggepinnen commented on test/clock.jl
>  sol = solve(prob, Tsit5(), kwargshandle = KeywordArgSilent)
sweet :) 

When we get to the stage where we can access discrete-time variables from the solution, I will be equally picky with exactly what index is obtained. `sol(k*dt, idxs=ud)` should get `ud` as computed for tick `k`, even if this variable happens to be called `u(k-1)` internally. When the solution object is plotted, the plot label should also refer to `u(t0 + k*dt)` as `u(k)`.

2024-03-19 09:39 UTC, AayushSabharwal commented on test/clock.jl
>  sol = solve(prob, Tsit5(), kwargshandle = KeywordArgSilent)
I think that shouldn't be too difficult

2024-03-19 10:34 UTC, baggepinnen commented on test/clock.jl
>  sol = solve(prob, Tsit5(), kwargshandle = KeywordArgSilent)
> It's somewhat of an artifact of using nonpositive shifts. Consider the continuous-time case

Is this analogy doing us any service? 

>  Similarly, for x(k) ~ f(x(k-1), x(k-2)) we take x(k-1) and x(k-2) as the unknowns, and compute x(k) which is now reinterpreted as "the next value of x(k-1)".

Just a comment on the terminology here. The fundamental _unknown_ is the discrete-time _function_ `x(k)` which is a function of the iteration index `k`. There is only one function `x`, and this function is defined on the domain `k \in {..., -1, 0, 1, 2, ...}`. In order to solve for this unknown function, we choose a _state realization_ comprised out of the _state variables_ `x(k-1), x(k-2)`. Here is where our discussion might become a bit confusing; It's quite common to change the names of the state variables completely into something more like
```
X(k) = [X1(k) X2(k)] = [x(k-1), x(k-2)]
```
so that you can speak about the (singular) _state_ at time index `k` being `X(k)`, and this state is comprised of the state variables `X(k) =  [X1(k) X2(k)] =[x(k-1), x(k-2)]`. In this discussion so far, we have conflated the unknown we are solving for with the state realization we have chosen in order to do so. The reason that these two are typically separated is partly to avoid this confusion.

Somewhat confusingly, MTK introduces new "unknowns" to represent the same function`x` but indexed at different points in time, like `x(k-1)` and `x(k-2)`, but I consider these unknowns computational tool rather than a property of the system being modeled. 

The terms "state" and "unknowns" are not interchangeable, which was the fundamental reason we made the switch from "states" (the plural form was wrong on so many levels) to "unknowns". After structural simplify, the term "state" is more descriptive, since structural simplification can be seen as the selection of a state realizaition among all the unknowns. 

> I think that shouldn't be too difficult

Probably not, but will it forever haunt us in the sense that every person looking into this in the future will be confused by the presence of a one-step shift in many places?


Sorry for all the long text here, I just want to make sure we fully understand each other very precisely and end up with a nice and maintainable solution that will be easy to communicate precisely to users so that we avoid the long list of bugs and confusions that plagued the old implementation.

2024-03-21 15:23 UTC, baggepinnen commented on test/discrete_system.jl
> +@variables S(t) I(t) R(t)
If I modify this problem to add an observable
```julia
@variables S(t) I(t) R(t) R2(t)

# Equations
eqs = [S ~ S(k - 1) - infection * h,
    I ~ I(k - 1) + infection - recovery,
    R ~ R(k - 1) + recovery,
    R2 ~ R]
```
and then try to plot the observed variable it does not work
```julia
julia> plot(sol_map, idxs=[R, R2])
ERROR: ArgumentError: R2(t) is neither an observed nor an unknown variable.
```

Will this somehow be handled?

2024-03-21 16:17 UTC, AayushSabharwal commented on test/discrete_system.jl
> +@variables S(t) I(t) R(t)
If you check `observed(sys)` you'll notice that it'll be something like `R2(k+1) ~ R + recovery` which is an artifact of shifting the entire system forward one timestep. Plotting `R2(k+1)` should work. While it's not great user API, it's the only way I found of making this correct, since in general we only have the capability of calculating the next state given the current state, even for observed variables.

Semantically, everything for `DiscreteSystem` should be correct. The saved values correspond to the states (i.e. `S(k)` is chosen to be a state, and the saved timeseries is for `S(k)`) and the observed equations are correct (albeit for the next timestep). Plotting `R2(k+1)` should plot a shifted `R(k)`. I haven't tested this, which I'll do and add to the testcases.

2024-03-21 23:53 UTC, ChrisRackauckas commented on test/discrete_system.jl
> +@variables S(t) I(t) R(t)
Can you open an issue about the user interface piece here and we merge?

2024-03-22 12:39 UTC, baggepinnen approved these changes
:tada:

2024-03-22 12:42 UTC, ChrisRackauckas commented on docs/src/tutorials/discrete_system.md
> +# (Experimental) Modeling Discrete Systems
Is it still experimental?

2024-03-22 12:45 UTC, baggepinnen commented on docs/src/tutorials/discrete_system.md
> +# (Experimental) Modeling Discrete Systems
kind of, unless observed variables are working as intended now?

2024-03-22 12:45 UTC, AayushSabharwal commented on docs/src/tutorials/discrete_system.md
> +# (Experimental) Modeling Discrete Systems
Yeah, since shifting the entire system by one step is basically a workaround and eventually we'll need proper compiler support for this. I've discussed with @baggepinnen and that will end up changing things such as the state realization and observed equations in the simplified system.

2024-03-22 13:26 UTC, ChrisRackauckas commented
Test failures

2024-03-22 13:59 UTC, AayushSabharwal commented
Fixed and rebased

2024-03-22 14:28 UTC, AayushSabharwal commented
CI failures are due to codecov

2024-03-22 14:49 UTC, merged

2024-03-22 14:56 UTC, AayushSabharwal commented
Finally 🥳