Add `getindex`/`setindex!` methods for `MTKParameters` with `ParameterIndex`
SciML/ModelingToolkit.jl pull request #2531
Opened 2024-03-10 14:14 UTC by MasonProtter

Without this method, we hit the generic methods for `MTKParameters` which assumes `ParameterIndex` is an integer

## Checklist

- [ ] Appropriate tests were added
- [ ] Any code changes were done in a way that does not break public API
- [ ] All documentation related to code changes were updated
- [ ] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [ ] Any new documentation only uses public API
  
## Additional context

2024-03-10 15:55 UTC, AayushSabharwal requested changes
`pind.idx` is not necessarily a 2-tuple. It can also have extra indices in case `p.portion[i][j]` is an array. For example, for `@parameters p[1:3]` you might have a `ParameterIndex(Tunable(), (2, 1, 2))` to refer to `p[2]`.

2024-03-10 18:14 UTC, MasonProtter commented
I see, thank you. does this change I just pushed make more sense?

2024-03-11 07:37 UTC, AayushSabharwal requested changes
I forgot this last time around 😅 but I think `setindex!` should just call `set_parameter!`. It handles the extra indexes, doesn't allow setting the dependent portion (as intended) and updates the dependent values.

2024-03-11 07:37 UTC, AayushSabharwal commented on src/systems/parameter_buffer.jl
> +        setindexer(p.dependent)
```suggestion
```
The dependent portion shouldn't be set directly

2024-03-11 09:38 UTC, MasonProtter commented on src/systems/parameter_buffer.jl
> +        setindexer(p.dependent)
Okay, I'd switched it to just fall back to `set_parameter`

2024-03-11 10:26 UTC, AayushSabharwal approved these changes
LGTM, but I don't have permissions to make CI run.

@ChrisRackauckas could you please approve CI

2024-03-11 13:00 UTC, ChrisRackauckas commented
Needs formatting

2024-03-11 18:10 UTC, MasonProtter commented
I added a basic testset to try and cover all the branches. Let me know if that's appropriate.

2024-03-11 19:14 UTC, ChrisRackauckas commented
Format's last PR

2024-03-12 02:23 UTC, merged