Fix `_varmap_to_vars`, re-enable dde.jl test
SciML/ModelingToolkit.jl pull request #2545
Opened 2024-03-13 13:41 UTC by MasonProtter

Closes https://github.com/SciML/ModelingToolkit.jl/issues/2543

cc @AayushSabharwal 

It turns out the problem was actually just that we weren't putting symbolic constraints into the `values` dict. I thought I had checked this before but I must have done something else that was breaking alongside it, so this took me way longer to track down than it should have.

This has made it so I can now re-enable the `dde.jl` test file which was previously excluded from the test suite. 

## Checklist

- [ ] Appropriate tests were added
- [ ] Any code changes were done in a way that does not break public API
- [ ] All documentation related to code changes were updated
- [ ] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [ ] Any new documentation only uses public API
  
## Additional context

Add any other context about the problem here.

2024-03-13 18:03 UTC, AayushSabharwal requested changes

2024-03-13 18:03 UTC, AayushSabharwal commented on src/variables.jl
> +        values[var] = val
Why is this necessary? This could fail in cases where a dependent initialization is not fully defined. For example, if `x => 2y` but `y` is not specified, `val` will be `2y` when we want it to not be a symbolic quantity.

2024-03-13 18:17 UTC, MasonProtter commented on src/variables.jl
> +        values[var] = val
This just restores the v8 behaviour. In v8 we had
```julia
function _varmap_to_vars(varmap::Dict, varlist; defaults = Dict(), check = false,
        toterm = Symbolics.diff2term)
    varmap = merge(defaults, varmap) # prefers the `varmap`
    varmap = Dict(toterm(value(k)) => value(varmap[k]) for k in keys(varmap))
    # resolve symbolic parameter expressions
    for (p, v) in pairs(varmap)
        varmap[p] = fixpoint_sub(v, varmap)
    end

    missingvars = setdiff(varlist, collect(keys(varmap)))
    check && (isempty(missingvars) || throw_missingvars(missingvars))

    out = [varmap[var] for var in varlist]
end
```
which was changed in v9 to only allow `values` to have non-symbolic entries, which caused this bug. 

e.g. in v8, for the test case linked above, `_varmap_to_vars` would take in arguments
```
varmap = Dict{Num, Num}(x₂(t) => 1.0 - 10q1*t, x₀(t) => 1.0 - 10q1*t, x₁(t) => 1.0 - 10q1*t)
varlist = SymbolicUtils.BasicSymbolic{Real}[x₀(t), x₁(t), x₂(t)]
defaults = Dict{Any, Any}(x₂(t) => 1.0 - 10q1*t, d2 => 1, beta0 => 1, v0 => 1, p0 => 0.2, d0 => 5, beta1 => 1, p1 => 0.2, q0 => 0.3, x₁(t) => 1.0 - 10q1*t, q1 => 0.3, d1 => 1, v1 => 1, x₀(t) => 1.0 - 10q1*t)
```
and compute
```julia
out = SymbolicUtils.BasicSymbolic{Real}[1.0 - 3.0t, 1.0 - 3.0t, 1.0 - 3.0t]
```

whereas in v9 we also have it taking in the identical arguments:
```julia
varmap = Dict{Num, Num}(x₂(t) => 1.0 - 10q1*t, x₀(t) => 1.0 - 10q1*t, x₁(t) => 1.0 - 10q1*t)
varlist = SymbolicUtils.BasicSymbolic{Real}[x₀(t), x₁(t), x₂(t)]
defaults = Dict{Any, Any}(x₂(t) => 1.0 - 10q1*t, d2 => 1, beta0 => 1, v0 => 1, p0 => 0.2, d0 => 5, beta1 => 1, p1 => 0.2, q0 => 0.3, x₁(t) => 1.0 - 10q1*t, q1 => 0.3, d1 => 1, v1 => 1, x₀(t) => 1.0 - 10q1*t)
```
and erroring. 

It's totally possible there's another way to fix this, but I *think* what I did is just the minimal change to un-break the change in v9.

2024-03-13 18:18 UTC, MasonProtter commented on src/systems/diffeqs/abstractodesystem.jl
> +    u0 = h(p..., tspan[1])
Right, sorry about that, I'll fix that

2024-03-13 18:29 UTC, MasonProtter commented on src/systems/diffeqs/abstractodesystem.jl
> +    u0 = h(p..., tspan[1])
should be fixed now, let me know if you see anything else potentially problematic

2024-03-14 05:20 UTC, AayushSabharwal commented
Please rebase and format so CI runs

2024-03-14 09:28 UTC, AayushSabharwal commented
Those commits shouldn't have appeared here after the rebase 😅

2024-03-14 09:55 UTC, MasonProtter commented
hmm, not sure what went wrong, I just configured `rebase = true` and pulled from master..

2024-03-14 10:07 UTC, AayushSabharwal commented
Try resetting to before the rebase using `git reflog`, then
```git
git checkout master
git pull sciml master # assuming sciml is the remote pointing to this repo
git checkout fix-dde
git rebase master
# fix conflicts
git push -f origin fix-dde
```

usually works for me

2024-03-14 10:29 UTC, MasonProtter commented
Aha, yeah I think I just did a bad order of operations or something, thank you for spelling it out.

2024-03-14 11:24 UTC, MasonProtter commented
So, comparing with https://github.com/SciML/ModelingToolkit.jl/pull/2548, it seems that there's an overall improvement here with a couple of previously failing suites now failing, and I'm not seeing any new regressions.

2024-03-14 11:32 UTC, AayushSabharwal commented
The failures in #2548 that don't fail here are due to codecov being flaky. This PR does have test regressions in `InterfaceI`. See: https://github.com/SciML/ModelingToolkit.jl/actions/runs/8279178750/job/22653091634?pr=2545#step:6:726

2024-03-20 13:30 UTC, ChrisRackauckas commented
What is the state of this?

2024-03-27 22:09 UTC, MasonProtter commented
Okay, this is finally working and ready to go. The failing downstream test is unrelated, and also present on other current PRs.

2024-03-28 06:42 UTC, AayushSabharwal requested changes
Just a couple minor comments. Looks good otherwise. Please also rebase this to remove commits such as `retrigger CI`.

2024-03-28 06:42 UTC, AayushSabharwal commented on Project.toml
> +DelayDiffEq = "bcd4f6db-9728-5f36-b5f7-82caef46ccdb"
This needs a compat bound

2024-03-28 06:42 UTC, AayushSabharwal commented on test/dde.jl
> +final_sys = structural_simplify(sys)
Can this just be an `@mtkbuild` instead of `@named`? Or is there a reason we need `sys` and `final_sys` separately?

2024-03-28 08:36 UTC, MasonProtter commented on Project.toml
> +DelayDiffEq = "bcd4f6db-9728-5f36-b5f7-82caef46ccdb"
It's only in the testing `[extras]`, it doesn't seem that any of the other extras have compat bounds.

2024-03-28 08:52 UTC, MasonProtter commented on test/dde.jl
> +final_sys = structural_simplify(sys)
nope, I've switched it to `@mtkbuild`

2024-03-28 08:54 UTC, MasonProtter commented
> Please also rebase this to remove commits such as `retrigger CI`.

I've rebased it, but you can also just use the `squash and merge` button.

2024-03-28 17:51 UTC, AayushSabharwal approved these changes

2024-03-28 17:59 UTC, merged