Fix observed functions with dependent parameters
SciML/ModelingToolkit.jl pull request #2668
Opened 2024-04-24 14:46 UTC by SebastianM-C

## Checklist

- [x] Appropriate tests were added
- [x] Any code changes were done in a way that does not break public API
- [x] All documentation related to code changes were updated
- [x] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [x] Any new documentation only uses public API
  
## Additional context

When `build_explicit_observed_function` was updated for parameter dependencies, only the `ps` argument was updated, but internally the function still ckecked for the `parameters` instead of the `full_parameters`.

2024-04-24 23:07 UTC, ChrisRackauckas commented
Format or the tests won't run.

2024-04-26 00:32 UTC, SebastianM-C commented
I realized that this is not enough, as the parameter dependencies are dropped in several other places. The above 2 are commits are what I got so far, I'm not sure what other places need this. I'll try to add more tests too.

2024-04-29 05:40 UTC, AayushSabharwal requested changes
This would also benefit from a test where a subsystem has a parameter dependency alongside the parent system it is included in. The subsystem's dependency should be appropriately namespaced

2024-04-29 05:40 UTC, AayushSabharwal commented on src/systems/diffeqs/odesystem.jl
> +            parameter_dependencies = get_parameter_dependencies(sys),
We could have parameter dependencies in hierarchical systems, which means this needs the `guesses` treatment where dependencies from subsystems are namespaced and included in the flattened system

2024-04-29 13:27 UTC, SebastianM-C commented on src/systems/diffeqs/odesystem.jl
> +            parameter_dependencies = get_parameter_dependencies(sys),
Isn't the system structurally simplified by the time we get here? [95c8567](https://github.com/SciML/ModelingToolkit.jl/pull/2668/commits/95c85674555414b40f6649312c8ff26e4d94796b) would take care of that.

2024-05-12 05:38 UTC, AayushSabharwal requested changes

2024-05-12 05:38 UTC, AayushSabharwal commented on test/parameter_dependencies.jl
> +
Could you also add a testcase for hierarchical systems where the subsystems have parameter dependencies? I have a feeling that will fail

2024-05-21 13:38 UTC, SebastianM-C commented on test/parameter_dependencies.jl
> +
Yeah, it failed. I added a test in [db89f68](https://github.com/SciML/ModelingToolkit.jl/pull/2668/commits/db89f6892a671c0bc80a807f7b3662833483385f) and I tried to do the renamespacing, but something is off and the dependent parameter does not seem to update correctly.

2024-05-21 14:00 UTC, SebastianM-C commented on src/systems/diffeqs/odesystem.jl
> +            parameter_dependencies = get_parameter_dependencies(sys),
I changed this to use `parameter_dependencies(sys)` instead, so now it gets the renamespaced dependencies of the subsystems.

2024-05-27 07:34 UTC, AayushSabharwal requested changes

2024-05-27 07:34 UTC, AayushSabharwal commented on src/systems/abstractsystem.jl
> +    Dict(dependent_parameters(sys, k) => namespace_expr(v, sys) for (k, v) in pdeps)
```suggestion
    Dict(parameters(sys, k) => namespace_expr(v, sys) for (k, v) in pdeps)
```

No need to create a new method that does the same thing as an old one

2024-05-27 07:34 UTC, AayushSabharwal commented on src/systems/abstractsystem.jl
> +    pdeps = get_parameter_dependencies(sys)
```suggestion
    pdeps = parameter_dependencies(sys)
```

This needs to be recursive, since we can have multiple levels of nesting

2024-05-27 07:34 UTC, AayushSabharwal commented on src/systems/abstractsystem.jl
> +        isnothing(get_parameter_dependencies(subsys)) && continue
```suggestion
```

Don't need this check for two reasons
- `subsys` might not have parameter dependencies, but subsystems of `subsys` might
- `namespace_parameter_dependencies` will handle checking subsystems of `subsys` by recursively calling this function

2024-05-27 07:34 UTC, AayushSabharwal commented on src/systems/abstractsystem.jl
> +
```suggestion
```

2024-05-27 07:34 UTC, AayushSabharwal commented on src/systems/index_cache.jl
> +        pdeps = parameter_dependencies(sys)
This is not technically necessary, although it will work regardless. If the system is simplified, all parameter dependencies will be available at the top level. If it isn't simplified, we can't simulate it anyway so an index cache is immaterial.

2024-05-27 07:34 UTC, AayushSabharwal commented on src/systems/nonlinear/initializesystem.jl
> +        parameter_dependencies = get_parameter_dependencies(sys),
```suggestion
        parameter_dependencies = parameter_dependencies(sys),
```

2024-05-27 07:35 UTC, AayushSabharwal commented
Also needs a rebase, since MTK CI passes now

2024-06-06 06:08 UTC, AayushSabharwal commented
I can't suggest changes on unchanged files, but in `src/systems/parameter_buffer.jl:139` `get_parameter_dependencies` needs to be `parameter_dependencies`. If you run a global search for `get_parameter_dependencies`, all of them except the ones in `parameter_dependencies` itself need to be replaced this way.

2024-06-06 12:45 UTC, SebastianM-C commented
Thanks! That seems to have solved the issue.

2024-06-06 16:10 UTC, AayushSabharwal approved these changes

2024-06-06 17:41 UTC, ChrisRackauckas approved these changes

2024-06-06 17:41 UTC, merged