WIP: Fix latexify support
SciML/ModelingToolkit.jl pull request #626
Opened 2020-10-29 09:52 UTC by korsbo

Latexification of MKT objects is broken. Here, I try to fix that. 

- [x] fix latexify for simple `Equation`s
- [ ] fix latexify for `Equation`s with higher-order derivatives #621
- [ ] fix latexify for `System`s (currently poorly implemented and surrounded by `$$`).

2020-10-29 09:54 UTC, korsbo commented
It would be good if someone who knows MTK could confirm that my changes to `toexpr` won't break anything. I have made minor corrections to the tests and I can't see any issues from there.

2020-10-30 12:32 UTC, korsbo commented
https://github.com/korsbo/Latexify.jl/pull/120 fixes the latexificaition of Systems.

2020-10-30 18:47 UTC, shashi commented on src/direct.jl
> +  return Expr(:call, toexpr(O.op), toexpr.(O.args)...)
We can't do this because it is wrong namespacing

2020-10-30 18:47 UTC, shashi commented on src/direct.jl
> +  return Expr(:call, toexpr(O.op), toexpr.(O.args)...)
Try using `Base.isoperator(nameof(f))` to check if `f` is an infix

2020-10-30 18:48 UTC, shashi requested changes

2020-10-30 18:48 UTC, shashi commented on test/simplify.jl
> +@test toexpr(simplify(x+2+3)) == :(5 + x)
Yeah this stuff was intentional

2020-10-30 19:14 UTC, shashi commented
Closing this in favor of #629 maybe a fix for #621 should come in a separate PR.

2020-10-30 19:14 UTC, closed without merging