Changed constructor to use sparsity_pattern() for sparse matrices
SciML/ModelingToolkit.jl pull request #966
Opened 2021-04-12 21:35 UTC by SamuelzXu

Attempt at closing #871 with help from @YingboMa

2021-04-12 21:43 UTC, ChrisRackauckas approved these changes

2021-04-12 21:48 UTC, SamuelzXu commented
@ChrisRackauckas how do I approach the SafeTestSets bug?

2021-04-12 21:50 UTC, ChrisRackauckas commented
What Safetestsets bug? I don't see one.

The error seems to be that you need to change the matrix from a matrix of booleans to a matrix of numbers.

2021-04-12 21:50 UTC, ChrisRackauckas commented on src/systems/diffeqs/abstractodesystem.jl
> +                     jac_prototype = sparse ? jacobian_sparsity(sys) : nothing, # similar(sys.jac[],Float64)
```suggestion
                     jac_prototype = sparse ? convert.((eltype(u0),),jacobian_sparsity(sys)) : nothing, # similar(sys.jac[],Float64)
```

2021-04-12 21:51 UTC, ChrisRackauckas commented on src/systems/diffeqs/abstractodesystem.jl
> +                     jac_prototype = sparse ? jacobian_sparsity(sys) : nothing, # similar(sys.jac[],Float64)
Actually hmm, how do you do that without a `u0` type? I guess you just guess Float64 for now?

2021-04-12 22:25 UTC, YingboMa requested changes
This is incorrect. We want use `sparsity_pattern` only when `jac=false` and `sparse=true`.

2021-04-12 22:28 UTC, ChrisRackauckas commented on src/systems/diffeqs/abstractodesystem.jl
> +        jac = sparsity_pattern(sys)
This should probably be reverted.

2021-04-12 22:30 UTC, ChrisRackauckas commented
I think you can achieve that by just using `jacobian_sparsity(sys)` in the ODEFunction construction? The issue from before was that `get_jac(sys)` would be building the full version just to create the Jacobian, which ended up full.

2021-04-13 14:42 UTC, YingboMa commented
You should also promote the `jac_prototype` to have the same `eltype` with `u0` in `ODEProblem` when you have `u0`.

2021-04-14 03:53 UTC, SamuelzXu commented
@YingboMa Hopefully this does the trick

2021-04-20 03:55 UTC, closed without merging